# Build and deploy Next.js app to Azure Web App

name: Build and deploy Next.js app to Azure Web App - Gamblefrontend

on:
  push:
    branches: [ main ]     # 只有 push 到 main 會觸發
  workflow_dispatch:       # 可以手動觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # 建議用 20 LTS，比 22 穩定

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: .              # 可以換成只打包需要的檔案，例如 .next, package.json

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Gamblefrontend'   # 你的 App Service 名稱
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
